Collage: MenuState Class Reference
MenuState Class Reference
#include <MenuState.h>
Public Member Functions
MenuState ()
void enter ()
void createScene ()
void exit ()
bool keyPressed (const OIS::KeyEvent &keyEventRef)
bool keyReleased (const OIS::KeyEvent &keyEventRef)
bool mouseMoved (const OIS::MouseEvent &evt)
bool mousePressed (const OIS::MouseEvent &evt, OIS::MouseButtonID id)
bool mouseReleased (const OIS::MouseEvent &evt, OIS::MouseButtonID id)
void buttonHit (OgreBites::Button *button)
void update (double timeSinceLastFrame)
Private Attributes
bool m_bQuit
Detailed Description
Definition at line 13 of file MenuState.h.
Constructor & Destructor Documentation
MenuState::MenuState ()
Definition at line 13 of file MenuState.cpp.
References m_bQuit, and AppState::m_FrameEvent.
Member Function Documentation
void MenuState::buttonHit (OgreBites::Button * button)
Definition at line 117 of file MenuState.cpp.
References AppState::findByName(), m_bQuit, and AppState::popAllAndPushAppState().
void MenuState::createScene ()
Definition at line 51 of file MenuState.cpp.
Referenced by enter().
void MenuState::enter () [virtual]
Implements AppState.
Definition at line 18 of file MenuState.cpp.
References createScene(), Singleton< UserInterface >::Instance(), Singleton< RenderEngine >::Instance(), Singleton< System >::Instance(), AppState::m_pCamera, and AppState::m_pSceneMgr.
void MenuState::exit () [virtual]
Implements AppState.
Definition at line 54 of file MenuState.cpp.
References Singleton< UserInterface >::Instance(), Singleton< RenderEngine >::Instance(), Singleton< System >::Instance(), AppState::m_pCamera, and AppState::m_pSceneMgr.
bool MenuState::keyPressed (const OIS::KeyEvent & keyEventRef)
Definition at line 67 of file MenuState.cpp.
References Singleton< Input >::Instance(), and m_bQuit.
bool MenuState::keyReleased (const OIS::KeyEvent & keyEventRef)
Definition at line 77 of file MenuState.cpp.
References Singleton< Input >::Instance().
bool MenuState::mouseMoved (const OIS::MouseEvent & evt)
Definition at line 82 of file MenuState.cpp.
References Singleton< UserInterface >::Instance().
bool MenuState::mousePressed (const OIS::MouseEvent & evt, OIS::MouseButtonID id)
Definition at line 88 of file MenuState.cpp.
References Singleton< UserInterface >::Instance().
bool MenuState::mouseReleased (const OIS::MouseEvent & evt, OIS::MouseButtonID id)
Definition at line 97 of file MenuState.cpp.
References Singleton< UserInterface >::Instance().
void MenuState::update (double timeSinceLastFrame) [virtual]
Implements AppState.
Definition at line 106 of file MenuState.cpp.
References Singleton< UserInterface >::Instance(), m_bQuit, AppState::m_FrameEvent, and AppState::shutdown().
Member Data Documentation
bool MenuState::m_bQuit [private]
Definition at line 35 of file MenuState.h.
Referenced by buttonHit(), keyPressed(), MenuState(), and update().
The documentation for this class was generated from the following files:
/home/bmonkey/workspace/Ogre/Collage/include/MenuState.h
/home/bmonkey/workspace/Ogre/Collage/src/State/MenuState.cpp