Collage: CollageApplication Class Reference
CollageApplication Class Reference
#include <CollageApplication.h>
Public Member Functions
CollageApplication ()
virtual ~CollageApplication ()
void start ()
Private Attributes
AppStateManager * m_pAppStateManager
Detailed Description
Definition at line 13 of file CollageApplication.h.
Constructor & Destructor Documentation
CollageApplication::CollageApplication ()
Definition at line 18 of file CollageApplication.cpp.
CollageApplication::~CollageApplication () [virtual]
Definition at line 21 of file CollageApplication.cpp.
Member Function Documentation
void CollageApplication::start ()
Definition at line 24 of file CollageApplication.cpp.
References AppState::create(), AppStateManager::findByName(), Singleton< System >::Instance(), Singleton< UserInterface >::Instance(), Singleton< Input >::Instance(), Singleton< RenderEngine >::Instance(), m_pAppStateManager, and AppStateManager::start().
Referenced by main().
Member Data Documentation
AppStateManager* CollageApplication::m_pAppStateManager [private]
Definition at line 20 of file CollageApplication.h.
Referenced by start().
The documentation for this class was generated from the following files:
/home/bmonkey/workspace/Ogre/Collage/include/CollageApplication.h
/home/bmonkey/workspace/Ogre/Collage/src/CollageApplication.cpp