Collage: GameState Class Reference
GameState Class Reference
#include <GameState.h>
Public Member Functions
GameState ()
void enter ()
void createScene ()
void exit ()
bool pause ()
void resume ()
void moveCamera ()
void getInput ()
void buildGUI ()
bool keyPressed (const OIS::KeyEvent &keyEventRef)
bool keyReleased (const OIS::KeyEvent &keyEventRef)
bool mouseMoved (const OIS::MouseEvent &arg)
bool mousePressed (const OIS::MouseEvent &arg, OIS::MouseButtonID id)
bool mouseReleased (const OIS::MouseEvent &arg, OIS::MouseButtonID id)
void onLeftPressed (const OIS::MouseEvent &evt)
void itemSelected (OgreBites::SelectMenu *menu)
void update (double timeSinceLastFrame)
Private Attributes
Ogre::SceneNode * m_pOgreHeadNode
Ogre::Entity * m_pOgreHeadEntity
Ogre::MaterialPtr m_pOgreHeadMat
Ogre::MaterialPtr m_pOgreHeadMatHigh
OgreBites::ParamsPanel * m_pDetailsPanel
bool m_bQuit
Ogre::Vector3 m_TranslateVector
Ogre::Real m_MoveSpeed
Ogre::Degree m_RotateSpeed
float m_MoveScale
Ogre::Degree m_RotScale
Ogre::RaySceneQuery * m_pRSQ
Ogre::SceneNode * m_pCurrentObject
Ogre::Entity * m_pCurrentEntity
bool m_bLMouseDown
bool m_bRMouseDown
bool m_bSettingsMode
Detailed Description
Definition at line 25 of file GameState.h.
Constructor & Destructor Documentation
GameState::GameState ()
Definition at line 13 of file GameState.cpp.
References m_bLMouseDown, m_bQuit, m_bRMouseDown, m_bSettingsMode, m_MoveSpeed, m_pCurrentObject, m_pDetailsPanel, and m_RotateSpeed.
Member Function Documentation
void GameState::buildGUI ()
Definition at line 314 of file GameState.cpp.
References Singleton< UserInterface >::Instance(), and m_pDetailsPanel.
Referenced by enter(), and resume().
void GameState::createScene ()
Definition at line 82 of file GameState.cpp.
References CUBE_MASK, m_pOgreHeadEntity, m_pOgreHeadMat, m_pOgreHeadMatHigh, m_pOgreHeadNode, AppState::m_pSceneMgr, OGRE_HEAD_MASK, and DotSceneLoader::parseDotScene().
Referenced by enter().
void GameState::enter () [virtual]
Implements AppState.
Definition at line 26 of file GameState.cpp.
References buildGUI(), createScene(), Singleton< RenderEngine >::Instance(), Singleton< System >::Instance(), AppState::m_pCamera, m_pRSQ, AppState::m_pSceneMgr, and OGRE_HEAD_MASK.
void GameState::exit () [virtual]
Implements AppState.
Definition at line 72 of file GameState.cpp.
References Singleton< RenderEngine >::Instance(), Singleton< System >::Instance(), AppState::m_pCamera, m_pRSQ, and AppState::m_pSceneMgr.
void GameState::getInput ()
Definition at line 256 of file GameState.cpp.
References Singleton< Input >::Instance(), m_bSettingsMode, m_MoveScale, and m_TranslateVector.
Referenced by update().
void GameState::itemSelected (OgreBites::SelectMenu * menu)
Definition at line 359 of file GameState.cpp.
References AppState::m_pCamera.
bool GameState::keyPressed (const OIS::KeyEvent & keyEventRef)
Definition at line 107 of file GameState.cpp.
References AppState::findByName(), Singleton< UserInterface >::Instance(), Singleton< Input >::Instance(), m_bSettingsMode, m_pDetailsPanel, and AppState::pushAppState().
bool GameState::keyReleased (const OIS::KeyEvent & keyEventRef)
Definition at line 167 of file GameState.cpp.
References Singleton< Input >::Instance().
bool GameState::mouseMoved (const OIS::MouseEvent & arg)
Definition at line 172 of file GameState.cpp.
References Singleton< UserInterface >::Instance(), m_bRMouseDown, and AppState::m_pCamera.
bool GameState::mousePressed (const OIS::MouseEvent & arg, OIS::MouseButtonID id)
Definition at line 184 of file GameState.cpp.
References Singleton< UserInterface >::Instance(), m_bLMouseDown, m_bRMouseDown, and onLeftPressed().
bool GameState::mouseReleased (const OIS::MouseEvent & arg, OIS::MouseButtonID id)
Definition at line 201 of file GameState.cpp.
References Singleton< UserInterface >::Instance(), m_bLMouseDown, and m_bRMouseDown.
void GameState::moveCamera ()
Definition at line 250 of file GameState.cpp.
References Singleton< Input >::Instance(), AppState::m_pCamera, and m_TranslateVector.
Referenced by update().
void GameState::onLeftPressed (const OIS::MouseEvent & evt)
Definition at line 217 of file GameState.cpp.
References Singleton< System >::Instance(), Singleton< Input >::Instance(), AppState::m_pCamera, m_pCurrentEntity, m_pCurrentObject, m_pOgreHeadMat, m_pOgreHeadMatHigh, m_pRSQ, and AppState::m_pSceneMgr.
Referenced by mousePressed().
bool GameState::pause () [virtual]
Reimplemented from AppState.
Definition at line 56 of file GameState.cpp.
References Singleton< System >::Instance().
void GameState::resume () [virtual]
Reimplemented from AppState.
Definition at line 62 of file GameState.cpp.
References buildGUI(), Singleton< RenderEngine >::Instance(), Singleton< System >::Instance(), m_bQuit, and AppState::m_pCamera.
void GameState::update (double timeSinceLastFrame) [virtual]
Implements AppState.
Definition at line 272 of file GameState.cpp.
References getInput(), Singleton< UserInterface >::Instance(), m_bQuit, m_bSettingsMode, AppState::m_FrameEvent, m_MoveScale, m_MoveSpeed, AppState::m_pCamera, m_pDetailsPanel, m_RotateSpeed, m_RotScale, m_TranslateVector, moveCamera(), and AppState::popAppState().
Member Data Documentation
bool GameState::m_bLMouseDown [private]
Definition at line 71 of file GameState.h.
Referenced by GameState(), mousePressed(), and mouseReleased().
bool GameState::m_bQuit [private]
Definition at line 60 of file GameState.h.
Referenced by GameState(), resume(), and update().
bool GameState::m_bRMouseDown [private]
Definition at line 71 of file GameState.h.
Referenced by GameState(), mouseMoved(), mousePressed(), and mouseReleased().
bool GameState::m_bSettingsMode [private]
Definition at line 72 of file GameState.h.
Referenced by GameState(), getInput(), keyPressed(), and update().
float GameState::m_MoveScale [private]
Definition at line 65 of file GameState.h.
Referenced by getInput(), and update().
Ogre::Real GameState::m_MoveSpeed [private]
Definition at line 63 of file GameState.h.
Referenced by GameState(), and update().
Ogre::Entity* GameState::m_pCurrentEntity [private]
Definition at line 70 of file GameState.h.
Referenced by onLeftPressed().
Ogre::SceneNode* GameState::m_pCurrentObject [private]
Definition at line 69 of file GameState.h.
Referenced by GameState(), and onLeftPressed().
OgreBites::ParamsPanel* GameState::m_pDetailsPanel [private]
Definition at line 59 of file GameState.h.
Referenced by buildGUI(), GameState(), keyPressed(), and update().
Ogre::Entity* GameState::m_pOgreHeadEntity [private]
Definition at line 55 of file GameState.h.
Referenced by createScene().
Ogre::MaterialPtr GameState::m_pOgreHeadMat [private]
Definition at line 56 of file GameState.h.
Referenced by createScene(), and onLeftPressed().
Ogre::MaterialPtr GameState::m_pOgreHeadMatHigh [private]
Definition at line 57 of file GameState.h.
Referenced by createScene(), and onLeftPressed().
Ogre::SceneNode* GameState::m_pOgreHeadNode [private]
Definition at line 54 of file GameState.h.
Referenced by createScene().
Ogre::RaySceneQuery* GameState::m_pRSQ [private]
Definition at line 68 of file GameState.h.
Referenced by enter(), exit(), and onLeftPressed().
Ogre::Degree GameState::m_RotateSpeed [private]
Definition at line 64 of file GameState.h.
Referenced by GameState(), and update().
Ogre::Degree GameState::m_RotScale [private]
Definition at line 66 of file GameState.h.
Referenced by update().
Ogre::Vector3 GameState::m_TranslateVector [private]
Definition at line 62 of file GameState.h.
Referenced by getInput(), moveCamera(), and update().
The documentation for this class was generated from the following files:
/home/bmonkey/workspace/Ogre/Collage/include/GameState.h
/home/bmonkey/workspace/Ogre/Collage/src/State/GameState.cpp