Collage: AppStateListener Class Reference
AppStateListener Class Reference
#include <AppStateListener.h>
Public Member Functions
AppStateListener ()
virtual ~AppStateListener ()
virtual void manageAppState (Ogre::String stateName, AppState *state)=0
virtual AppState * findByName (Ogre::String stateName)=0
virtual void changeAppState (AppState *state)=0
virtual bool pushAppState (AppState *state)=0
virtual void popAppState ()=0
virtual void pauseAppState (AppState *state)=0
virtual void shutdown ()=0
virtual void popAllAndPushAppState (AppState *state)=0
Detailed Description
Definition at line 15 of file AppStateListener.h.
Constructor & Destructor Documentation
AppStateListener::AppStateListener () [inline]
Definition at line 17 of file AppStateListener.h.
virtual AppStateListener::~AppStateListener () [inline, virtual]
Definition at line 18 of file AppStateListener.h.
Member Function Documentation
virtual void AppStateListener::changeAppState (AppState * state) [pure virtual]
Implemented in AppStateManager.
Referenced by AppState::changeAppState().
virtual AppState* AppStateListener::findByName (Ogre::String stateName) [pure virtual]
Implemented in AppStateManager.
Referenced by AppState::findByName().
virtual void AppStateListener::manageAppState (Ogre::String stateName, AppState * state) [pure virtual]
Implemented in AppStateManager.
virtual void AppStateListener::pauseAppState (AppState * state) [pure virtual]
Implemented in AppStateManager.
virtual void AppStateListener::popAllAndPushAppState (AppState * state) [pure virtual]
Implemented in AppStateManager.
Referenced by AppState::popAllAndPushAppState().
virtual void AppStateListener::popAppState () [pure virtual]
Implemented in AppStateManager.
Referenced by AppState::popAppState().
virtual bool AppStateListener::pushAppState (AppState * state) [pure virtual]
Implemented in AppStateManager.
Referenced by AppState::pushAppState().
virtual void AppStateListener::shutdown () [pure virtual]
Implemented in AppStateManager.
Referenced by AppState::shutdown().
The documentation for this class was generated from the following file:
/home/bmonkey/workspace/Ogre/Collage/include/AppStateListener.h