Collage: AppStateManager Class Reference
AppStateManager Class Reference
#include <AppStateManager.h>
Classes
struct state_info
Public Member Functions
AppStateManager ()
~AppStateManager ()
void manageAppState (Ogre::String stateName, AppState *state)
AppState * findByName (Ogre::String stateName)
void start (AppState *state)
void changeAppState (AppState *state)
bool pushAppState (AppState *state)
void popAppState (void)
void pauseAppState (AppState *state)
void shutdown (void)
void popAllAndPushAppState (AppState *state)
Protected Member Functions
void init (AppState *state)
Protected Attributes
std::vector< AppState * > m_ActiveStateStack
std::vector< state_info > m_States
bool m_bShutdown
Detailed Description
Definition at line 14 of file AppStateManager.h.
Constructor & Destructor Documentation
AppStateManager::AppStateManager ()
Definition at line 17 of file AppStateManager.cpp.
References m_bShutdown.
AppStateManager::~AppStateManager ()
Definition at line 22 of file AppStateManager.cpp.
References m_ActiveStateStack, and m_States.
Member Function Documentation
void AppStateManager::changeAppState (AppState * state) [virtual]
Implements AppStateListener.
Definition at line 95 of file AppStateManager.cpp.
References init(), and m_ActiveStateStack.
Referenced by start().
AppState * AppStateManager::findByName (Ogre::String stateName) [virtual]
Implements AppStateListener.
Definition at line 47 of file AppStateManager.cpp.
References m_States.
Referenced by CollageApplication::start().
void AppStateManager::init (AppState * state) [protected]
Definition at line 146 of file AppStateManager.cpp.
References Singleton< RenderEngine >::Instance(), Singleton< UserInterface >::Instance(), and Singleton< Input >::Instance().
Referenced by changeAppState(), popAppState(), and pushAppState().
void AppStateManager::manageAppState (Ogre::String stateName, AppState * state) [virtual]
Implements AppStateListener.
Definition at line 33 of file AppStateManager.cpp.
References m_States, AppStateManager::state_info::name, and AppStateManager::state_info::state.
void AppStateManager::pauseAppState (AppState * state) [virtual]
Implements AppStateListener.
Definition at line 154 of file AppStateManager.cpp.
void AppStateManager::popAllAndPushAppState (AppState * state) [virtual]
Implements AppStateListener.
Definition at line 133 of file AppStateManager.cpp.
References m_ActiveStateStack, and pushAppState().
void AppStateManager::popAppState (void) [virtual]
Implements AppStateListener.
Definition at line 119 of file AppStateManager.cpp.
References init(), m_ActiveStateStack, and shutdown().
bool AppStateManager::pushAppState (AppState * state) [virtual]
Implements AppStateListener.
Definition at line 106 of file AppStateManager.cpp.
References init(), and m_ActiveStateStack.
Referenced by popAllAndPushAppState().
void AppStateManager::shutdown (void) [virtual]
Implements AppStateListener.
Definition at line 142 of file AppStateManager.cpp.
References m_bShutdown.
Referenced by popAppState().
void AppStateManager::start (AppState * state)
Definition at line 58 of file AppStateManager.cpp.
References changeAppState(), Singleton< Input >::Instance(), Singleton< System >::Instance(), Singleton< RenderEngine >::Instance(), m_ActiveStateStack, and m_bShutdown.
Referenced by CollageApplication::start().
Member Data Documentation
std::vector<AppState*> AppStateManager::m_ActiveStateStack [protected]
Definition at line 39 of file AppStateManager.h.
Referenced by changeAppState(), popAllAndPushAppState(), popAppState(), pushAppState(), start(), and ~AppStateManager().
bool AppStateManager::m_bShutdown [protected]
Definition at line 41 of file AppStateManager.h.
Referenced by AppStateManager(), shutdown(), and start().
std::vector<state_info> AppStateManager::m_States [protected]
Definition at line 40 of file AppStateManager.h.
Referenced by findByName(), manageAppState(), and ~AppStateManager().
The documentation for this class was generated from the following files:
/home/bmonkey/workspace/Ogre/Collage/include/AppStateManager.h
/home/bmonkey/workspace/Ogre/Collage/src/State/AppStateManager.cpp