Collage: PauseState Class Reference
PauseState Class Reference
#include <PauseState.h>
Public Member Functions
PauseState ()
void enter ()
void createScene ()
void exit ()
bool keyPressed (const OIS::KeyEvent &keyEventRef)
bool keyReleased (const OIS::KeyEvent &keyEventRef)
bool mouseMoved (const OIS::MouseEvent &evt)
bool mousePressed (const OIS::MouseEvent &evt, OIS::MouseButtonID id)
bool mouseReleased (const OIS::MouseEvent &evt, OIS::MouseButtonID id)
void buttonHit (OgreBites::Button *button)
void yesNoDialogClosed (const Ogre::DisplayString &question, bool yesHit)
void update (double timeSinceLastFrame)
Private Attributes
bool m_bQuit
Detailed Description
Definition at line 13 of file PauseState.h.
Constructor & Destructor Documentation
PauseState::PauseState ()
Definition at line 12 of file PauseState.cpp.
References m_bQuit, and AppState::m_FrameEvent.
Member Function Documentation
void PauseState::buttonHit (OgreBites::Button * button)
Definition at line 121 of file PauseState.cpp.
References AppState::findByName(), Singleton< UserInterface >::Instance(), m_bQuit, and AppState::popAllAndPushAppState().
void PauseState::createScene ()
Definition at line 54 of file PauseState.cpp.
Referenced by enter().
void PauseState::enter () [virtual]
Implements AppState.
Definition at line 17 of file PauseState.cpp.
References createScene(), Singleton< UserInterface >::Instance(), Singleton< RenderEngine >::Instance(), Singleton< System >::Instance(), m_bQuit, AppState::m_pCamera, and AppState::m_pSceneMgr.
void PauseState::exit () [virtual]
Implements AppState.
Definition at line 58 of file PauseState.cpp.
References Singleton< UserInterface >::Instance(), Singleton< RenderEngine >::Instance(), Singleton< System >::Instance(), AppState::m_pCamera, and AppState::m_pSceneMgr.
bool PauseState::keyPressed (const OIS::KeyEvent & keyEventRef)
Definition at line 71 of file PauseState.cpp.
References Singleton< Input >::Instance(), and m_bQuit.
bool PauseState::keyReleased (const OIS::KeyEvent & keyEventRef)
Definition at line 82 of file PauseState.cpp.
References Singleton< Input >::Instance().
bool PauseState::mouseMoved (const OIS::MouseEvent & evt)
Definition at line 88 of file PauseState.cpp.
References Singleton< UserInterface >::Instance().
bool PauseState::mousePressed (const OIS::MouseEvent & evt, OIS::MouseButtonID id)
Definition at line 94 of file PauseState.cpp.
References Singleton< UserInterface >::Instance().
bool PauseState::mouseReleased (const OIS::MouseEvent & evt, OIS::MouseButtonID id)
Definition at line 103 of file PauseState.cpp.
References Singleton< UserInterface >::Instance().
void PauseState::update (double timeSinceLastFrame) [virtual]
Implements AppState.
Definition at line 110 of file PauseState.cpp.
References Singleton< UserInterface >::Instance(), m_bQuit, AppState::m_FrameEvent, and AppState::popAppState().
void PauseState::yesNoDialogClosed (const Ogre::DisplayString & question, bool yesHit)
Definition at line 131 of file PauseState.cpp.
References Singleton< UserInterface >::Instance(), and AppState::shutdown().
Member Data Documentation
bool PauseState::m_bQuit [private]
Definition at line 36 of file PauseState.h.
Referenced by buttonHit(), enter(), keyPressed(), PauseState(), and update().
The documentation for this class was generated from the following files:
/home/bmonkey/workspace/Ogre/Collage/include/PauseState.h
/home/bmonkey/workspace/Ogre/Collage/src/State/PauseState.cpp