Collage: rapidxml::xml_document< Ch > Class Template Reference
rapidxml::xml_document< Ch > Class Template Reference
#include <rapidxml.hpp>
Classes
struct attribute_name_pred
struct attribute_value_pred
struct attribute_value_pure_pred
struct node_name_pred
struct text_pred
struct text_pure_no_ws_pred
struct text_pure_with_ws_pred
struct whitespace_pred
Public Member Functions
xml_document ()
Constructs empty XML document.
template<int Flags>
void parse (Ch *text)
void clear ()
Private Member Functions
template<int Flags>
void parse_bom (Ch *&text)
template<int Flags>
xml_node< Ch > * parse_xml_declaration (Ch *&text)
template<int Flags>
xml_node< Ch > * parse_comment (Ch *&text)
template<int Flags>
xml_node< Ch > * parse_doctype (Ch *&text)
template<int Flags>
xml_node< Ch > * parse_pi (Ch *&text)
template<int Flags>
Ch parse_and_append_data (xml_node< Ch > *node, Ch *&text, Ch *contents_start)
template<int Flags>
xml_node< Ch > * parse_cdata (Ch *&text)
template<int Flags>
xml_node< Ch > * parse_element (Ch *&text)
template<int Flags>
xml_node< Ch > * parse_node (Ch *&text)
template<int Flags>
void parse_node_contents (Ch *&text, xml_node< Ch > *node)
template<int Flags>
void parse_node_attributes (Ch *&text, xml_node< Ch > *node)
Static Private Member Functions
template<int Flags>
static void insert_coded_character (Ch *&text, unsigned long code)
template<class StopPred , int Flags>
static void skip (Ch *&text)
template<class StopPred , class StopPredPure , int Flags>
static Ch * skip_and_expand_character_refs (Ch *&text)
Detailed Description
template<class Ch = char>
class rapidxml::xml_document< Ch >
This class represents root of the DOM hierarchy. It is also an xml_node and a memory_pool through public inheritance. Use parse() function to build a DOM tree from a zero-terminated XML text string. parse() function allocates memory for nodes and attributes by using functions of xml_document, which are inherited from memory_pool. To access root node of the document, use the document itself, as if it was an xml_node.
Parameters:
Ch Character type to use.
Definition at line 1358 of file rapidxml.hpp.
Constructor & Destructor Documentation
template<class Ch = char> rapidxml::xml_document< Ch >::xml_document () [inline]
Constructs empty XML document.
Definition at line 1364 of file rapidxml.hpp.
Member Function Documentation
template<class Ch = char> void rapidxml::xml_document< Ch >::clear () [inline]
Clears the document by deleting all nodes and clearing the memory pool. All nodes owned by document pool are destroyed.
Reimplemented from rapidxml::memory_pool< Ch >.
Definition at line 1415 of file rapidxml.hpp.
References rapidxml::xml_node< Ch >::remove_all_attributes(), and rapidxml::xml_node< Ch >::remove_all_nodes().
template<class Ch = char> template<int Flags> static void rapidxml::xml_document< Ch >::insert_coded_character (Ch *& text, unsigned long code) [inline, static, private]
Definition at line 1511 of file rapidxml.hpp.
References rapidxml::parse_no_utf8, and RAPIDXML_PARSE_ERROR.
template<class Ch = char> template<int Flags> void rapidxml::xml_document< Ch >::parse (Ch * text) [inline]
Parses zero-terminated XML string according to given flags. Passed string will be modified by the parser, unless rapidxml::parse_non_destructive flag is used. The string must persist for the lifetime of the document. In case of error, rapidxml::parse_error exception will be thrown.
If you want to parse contents of a file, you must first load the file into the memory, and pass pointer to its beginning. Make sure that data is zero-terminated.
Document can be parsed into multiple times. Each new call to parse removes previous nodes and attributes (if any), but does not clear memory pool.
Parameters:
text XML data to parse; pointer is non-const to denote fact that this data may be modified by the parser.
Definition at line 1381 of file rapidxml.hpp.
References rapidxml::xml_node< Ch >::append_node(), RAPIDXML_PARSE_ERROR, rapidxml::xml_node< Ch >::remove_all_attributes(), and rapidxml::xml_node< Ch >::remove_all_nodes().
Referenced by DotSceneLoader::parseDotScene().
template<class Ch = char> template<int Flags> Ch rapidxml::xml_document< Ch >::parse_and_append_data (xml_node< Ch > * node, Ch *& text, Ch * contents_start) [inline, private]
Definition at line 1940 of file rapidxml.hpp.
References rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::xml_node< Ch >::append_node(), rapidxml::node_data, rapidxml::parse_no_data_nodes, rapidxml::parse_no_element_values, rapidxml::parse_no_string_terminators, rapidxml::parse_normalize_whitespace, rapidxml::parse_trim_whitespace, rapidxml::xml_document< Ch >::whitespace_pred::test(), and rapidxml::xml_base< Ch >::value().
template<class Ch = char> template<int Flags> void rapidxml::xml_document< Ch >::parse_bom (Ch *& text) [inline, private]
Definition at line 1725 of file rapidxml.hpp.
template<class Ch = char> template<int Flags> xml_node<Ch>* rapidxml::xml_document< Ch >::parse_cdata (Ch *& text) [inline, private]
Definition at line 1998 of file rapidxml.hpp.
References rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::node_cdata, rapidxml::parse_no_data_nodes, rapidxml::parse_no_string_terminators, RAPIDXML_PARSE_ERROR, and rapidxml::xml_base< Ch >::value().
template<class Ch = char> template<int Flags> xml_node<Ch>* rapidxml::xml_document< Ch >::parse_comment (Ch *& text) [inline, private]
Definition at line 1773 of file rapidxml.hpp.
References rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::node_comment, rapidxml::parse_comment_nodes, rapidxml::parse_no_string_terminators, RAPIDXML_PARSE_ERROR, and rapidxml::xml_base< Ch >::value().
template<class Ch = char> template<int Flags> xml_node<Ch>* rapidxml::xml_document< Ch >::parse_doctype (Ch *& text) [inline, private]
Definition at line 1814 of file rapidxml.hpp.
References rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::node_doctype, rapidxml::parse_doctype_node, rapidxml::parse_no_string_terminators, RAPIDXML_PARSE_ERROR, and rapidxml::xml_base< Ch >::value().
template<class Ch = char> template<int Flags> xml_node<Ch>* rapidxml::xml_document< Ch >::parse_element (Ch *& text) [inline, private]
Definition at line 2037 of file rapidxml.hpp.
References rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::xml_base< Ch >::name(), rapidxml::xml_base< Ch >::name_size(), rapidxml::node_element, rapidxml::parse_no_string_terminators, and RAPIDXML_PARSE_ERROR.
template<class Ch = char> template<int Flags> xml_node<Ch>* rapidxml::xml_document< Ch >::parse_node (Ch *& text) [inline, private]
Definition at line 2081 of file rapidxml.hpp.
References RAPIDXML_PARSE_ERROR, and rapidxml::xml_document< Ch >::whitespace_pred::test().
template<class Ch = char> template<int Flags> void rapidxml::xml_document< Ch >::parse_node_attributes (Ch *& text, xml_node< Ch > * node) [inline, private]
Definition at line 2237 of file rapidxml.hpp.
References rapidxml::memory_pool< Ch >::allocate_attribute(), rapidxml::xml_node< Ch >::append_attribute(), rapidxml::xml_base< Ch >::name(), rapidxml::xml_base< Ch >::name_size(), rapidxml::parse_no_string_terminators, rapidxml::parse_normalize_whitespace, RAPIDXML_PARSE_ERROR, rapidxml::xml_document< Ch >::skip_and_expand_character_refs(), rapidxml::xml_document< Ch >::attribute_name_pred::test(), rapidxml::xml_base< Ch >::value(), and rapidxml::xml_base< Ch >::value_size().
template<class Ch = char> template<int Flags> void rapidxml::xml_document< Ch >::parse_node_contents (Ch *& text, xml_node< Ch > * node) [inline, private]
Definition at line 2167 of file rapidxml.hpp.
References rapidxml::xml_node< Ch >::append_node(), rapidxml::xml_base< Ch >::name(), rapidxml::xml_base< Ch >::name_size(), rapidxml::parse_validate_closing_tags, and RAPIDXML_PARSE_ERROR.
template<class Ch = char> template<int Flags> xml_node<Ch>* rapidxml::xml_document< Ch >::parse_pi (Ch *& text) [inline, private]
Definition at line 1880 of file rapidxml.hpp.
References rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::xml_base< Ch >::name(), rapidxml::xml_base< Ch >::name_size(), rapidxml::node_pi, rapidxml::parse_no_string_terminators, rapidxml::parse_pi_nodes, RAPIDXML_PARSE_ERROR, rapidxml::xml_base< Ch >::value(), and rapidxml::xml_base< Ch >::value_size().
template<class Ch = char> template<int Flags> xml_node<Ch>* rapidxml::xml_document< Ch >::parse_xml_declaration (Ch *& text) [inline, private]
Definition at line 1738 of file rapidxml.hpp.
References rapidxml::memory_pool< Ch >::allocate_node(), rapidxml::node_declaration, rapidxml::parse_declaration_node, and RAPIDXML_PARSE_ERROR.
template<class Ch = char> template<class StopPred , int Flags> static void rapidxml::xml_document< Ch >::skip (Ch *& text) [inline, static, private]
Definition at line 1558 of file rapidxml.hpp.
template<class Ch = char> template<class StopPred , class StopPredPure , int Flags> static Ch* rapidxml::xml_document< Ch >::skip_and_expand_character_refs (Ch *& text) [inline, static, private]
Definition at line 1570 of file rapidxml.hpp.
References rapidxml::parse_no_entity_translation, rapidxml::parse_normalize_whitespace, rapidxml::parse_trim_whitespace, RAPIDXML_PARSE_ERROR, and rapidxml::xml_document< Ch >::whitespace_pred::test().
Referenced by rapidxml::xml_document< Ch >::parse_node_attributes().
The documentation for this class was generated from the following file:
/home/bmonkey/workspace/Ogre/Collage/include/rapidxml.hpp