Collage: DotSceneLoader Class Reference
DotSceneLoader Class Reference
#include <DotSceneLoader.h>
Public Member Functions
DotSceneLoader ()
virtual ~DotSceneLoader ()
void parseDotScene (const Ogre::String &SceneName, const Ogre::String &groupName, Ogre::SceneManager *yourSceneMgr, Ogre::SceneNode *pAttachNode=NULL, const Ogre::String &sPrependNode="")
Ogre::String getProperty (const Ogre::String &ndNm, const Ogre::String &prop)
Ogre::TerrainGroup * getTerrainGroup ()
Public Attributes
Ogre::TerrainGlobalOptions * mTerrainGlobalOptions
std::vector< nodeProperty > nodeProperties
std::vector< Ogre::String > staticObjects
std::vector< Ogre::String > dynamicObjects
std::vector
< Forests::PagedGeometry * > mPGHandles
std::vector
< Forests::TreeLoader3D * > mTreeHandles
Protected Member Functions
void processScene (rapidxml::xml_node<> *XMLRoot)
void processNodes (rapidxml::xml_node<> *XMLNode)
void processExternals (rapidxml::xml_node<> *XMLNode)
void processEnvironment (rapidxml::xml_node<> *XMLNode)
void processTerrain (rapidxml::xml_node<> *XMLNode)
void processTerrainPage (rapidxml::xml_node<> *XMLNode)
void processBlendmaps (rapidxml::xml_node<> *XMLNode)
void processUserDataReference (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent=0)
void processUserDataReference (rapidxml::xml_node<> *XMLNode, Ogre::Entity *pEntity)
void processOctree (rapidxml::xml_node<> *XMLNode)
void processLight (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent=0)
void processCamera (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent=0)
void processNode (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent=0)
void processLookTarget (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent)
void processTrackTarget (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent)
void processEntity (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent)
void processParticleSystem (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent)
void processBillboardSet (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent)
void processPlane (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent)
void processPagedGeometry (rapidxml::xml_node<> *XMLNode, Ogre::SceneNode *pParent)
void processFog (rapidxml::xml_node<> *XMLNode)
void processSkyBox (rapidxml::xml_node<> *XMLNode)
void processSkyDome (rapidxml::xml_node<> *XMLNode)
void processSkyPlane (rapidxml::xml_node<> *XMLNode)
void processClipping (rapidxml::xml_node<> *XMLNode)
void processLightRange (rapidxml::xml_node<> *XMLNode, Ogre::Light *pLight)
void processLightAttenuation (rapidxml::xml_node<> *XMLNode, Ogre::Light *pLight)
Ogre::String getAttrib (rapidxml::xml_node<> *XMLNode, const Ogre::String &parameter, const Ogre::String &defaultValue="")
Ogre::Real getAttribReal (rapidxml::xml_node<> *XMLNode, const Ogre::String &parameter, Ogre::Real defaultValue=0)
bool getAttribBool (rapidxml::xml_node<> *XMLNode, const Ogre::String &parameter, bool defaultValue=false)
Ogre::Vector3 parseVector3 (rapidxml::xml_node<> *XMLNode)
Ogre::Quaternion parseQuaternion (rapidxml::xml_node<> *XMLNode)
Ogre::ColourValue parseColour (rapidxml::xml_node<> *XMLNode)
Protected Attributes
Ogre::SceneManager * mSceneMgr
Ogre::SceneNode * mAttachNode
Ogre::String m_sGroupName
Ogre::String m_sPrependNode
Ogre::TerrainGroup * mTerrainGroup
Ogre::Vector3 mTerrainPosition
Ogre::Vector3 mLightDirection
Detailed Description
Definition at line 47 of file DotSceneLoader.h.
Constructor & Destructor Documentation
DotSceneLoader::DotSceneLoader ()
Definition at line 26 of file DotSceneLoader.cpp.
References mTerrainGlobalOptions.
DotSceneLoader::~DotSceneLoader () [virtual]
Definition at line 32 of file DotSceneLoader.cpp.
References mTerrainGlobalOptions, and mTerrainGroup.
Member Function Documentation
Ogre::String DotSceneLoader::getAttrib (rapidxml::xml_node<> * XMLNode, const Ogre::String & parameter, const Ogre::String & defaultValue = "") [protected]
Definition at line 991 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute().
Referenced by parseDotScene(), processCamera(), processEntity(), processFog(), processLight(), processLookTarget(), processNode(), processPagedGeometry(), processParticleSystem(), processPlane(), processScene(), processSkyBox(), processSkyPlane(), processTerrainPage(), and processTrackTarget().
bool DotSceneLoader::getAttribBool (rapidxml::xml_node<> * XMLNode, const Ogre::String & parameter, bool defaultValue = false) [protected]
Definition at line 1008 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute().
Referenced by processEntity(), processLight(), processNode(), processPlane(), processSkyBox(), processSkyDome(), processSkyPlane(), and processTerrain().
Ogre::Real DotSceneLoader::getAttribReal (rapidxml::xml_node<> * XMLNode, const Ogre::String & parameter, Ogre::Real defaultValue = 0) [protected]
Definition at line 999 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute().
Referenced by processCamera(), processClipping(), processFog(), processLightAttenuation(), processLightRange(), processPagedGeometry(), processPlane(), processSkyBox(), processSkyDome(), processSkyPlane(), and processTerrain().
Ogre::String DotSceneLoader::getProperty (const Ogre::String & ndNm, const Ogre::String & prop)
Definition at line 1111 of file DotSceneLoader.cpp.
References nodeProperties.
Ogre::TerrainGroup* DotSceneLoader::getTerrainGroup () [inline]
Definition at line 61 of file DotSceneLoader.h.
References mTerrainGroup.
Ogre::ColourValue DotSceneLoader::parseColour (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 1098 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute().
Referenced by processEnvironment(), processFog(), and processLight().
void DotSceneLoader::parseDotScene (const Ogre::String & SceneName, const Ogre::String & groupName, Ogre::SceneManager * yourSceneMgr, Ogre::SceneNode * pAttachNode = NULL, const Ogre::String & sPrependNode = "")
Definition at line 62 of file DotSceneLoader.cpp.
References dynamicObjects, rapidxml::xml_node< Ch >::first_node(), getAttrib(), m_sGroupName, m_sPrependNode, mAttachNode, mSceneMgr, rapidxml::xml_document< Ch >::parse(), processScene(), and staticObjects.
Referenced by GameState::createScene().
Ogre::Quaternion DotSceneLoader::parseQuaternion (rapidxml::xml_node<> * XMLNode) [protected]
Todo:
Fix this crap!
Definition at line 1029 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute().
Referenced by processCamera(), processNode(), processNodes(), processSkyBox(), and processSkyDome().
Ogre::Vector3 DotSceneLoader::parseVector3 (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 1020 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute().
Referenced by processCamera(), processLight(), processLookTarget(), processNode(), processNodes(), processPagedGeometry(), processPlane(), and processTrackTarget().
void DotSceneLoader::processBillboardSet (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent) [protected]
Todo:
Implement this
Definition at line 739 of file DotSceneLoader.cpp.
Referenced by processNode().
void DotSceneLoader::processBlendmaps (rapidxml::xml_node<> * XMLNode) [protected]
void DotSceneLoader::processCamera (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent = 0) [protected]
Todo:
Is this always in degrees?
<
Todo:
What to do with this element?
<
Todo:
Implement the camera look target
<
Todo:
Implement the camera track target
<
Todo:
Implement the camera user data reference
Definition at line 395 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), getAttrib(), getAttribReal(), mAttachNode, mSceneMgr, parseQuaternion(), and parseVector3().
Referenced by processEnvironment(), processNode(), and processScene().
void DotSceneLoader::processClipping (rapidxml::xml_node<> * XMLNode) [protected]
Todo:
Implement this
Definition at line 960 of file DotSceneLoader.cpp.
References getAttribReal().
Referenced by processEnvironment().
void DotSceneLoader::processEntity (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent) [protected]
Definition at line 670 of file DotSceneLoader.cpp.
References dynamicObjects, rapidxml::xml_node< Ch >::first_node(), getAttrib(), getAttribBool(), m_sGroupName, mSceneMgr, processUserDataReference(), and staticObjects.
Referenced by processNode().
void DotSceneLoader::processEnvironment (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 204 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), mSceneMgr, parseColour(), processCamera(), processClipping(), processFog(), processSkyBox(), processSkyDome(), processSkyPlane(), and processUserDataReference().
Referenced by processScene().
void DotSceneLoader::processExternals (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 201 of file DotSceneLoader.cpp.
Referenced by processScene().
void DotSceneLoader::processFog (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 863 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), getAttrib(), getAttribReal(), mSceneMgr, and parseColour().
Referenced by processEnvironment().
void DotSceneLoader::processLight (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent = 0) [protected]
Definition at line 326 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), getAttrib(), getAttribBool(), mLightDirection, mSceneMgr, parseColour(), parseVector3(), processLightAttenuation(), and processLightRange().
void DotSceneLoader::processLightAttenuation (rapidxml::xml_node<> * XMLNode, Ogre::Light * pLight) [protected]
Definition at line 979 of file DotSceneLoader.cpp.
References getAttribReal().
Referenced by processLight().
void DotSceneLoader::processLightRange (rapidxml::xml_node<> * XMLNode, Ogre::Light * pLight) [protected]
Definition at line 968 of file DotSceneLoader.cpp.
References getAttribReal().
Referenced by processLight().
void DotSceneLoader::processLookTarget (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent) [protected]
Todo:
Is this correct? Cause I don't have a clue actually
Definition at line 597 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), getAttrib(), mSceneMgr, and parseVector3().
Referenced by processNode().
void DotSceneLoader::processNode (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent = 0) [protected]
Definition at line 476 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), getAttrib(), getAttribBool(), m_sPrependNode, mAttachNode, rapidxml::xml_node< Ch >::next_sibling(), parseQuaternion(), parseVector3(), processBillboardSet(), processCamera(), processEntity(), processLookTarget(), processPagedGeometry(), processParticleSystem(), processPlane(), processTrackTarget(), and processUserDataReference().
Referenced by processNodes().
void DotSceneLoader::processNodes (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 169 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), mAttachNode, rapidxml::xml_node< Ch >::next_sibling(), parseQuaternion(), parseVector3(), and processNode().
Referenced by processScene().
void DotSceneLoader::processOctree (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 323 of file DotSceneLoader.cpp.
Referenced by processScene().
void DotSceneLoader::processPagedGeometry (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent) [protected]
Definition at line 782 of file DotSceneLoader.cpp.
References getAttrib(), getAttribReal(), mSceneMgr, ParseStringVector(), parseVector3(), PGInstanceInfo::pos, PGInstanceInfo::scale, and PGInstanceInfo::yaw.
Referenced by processNode().
void DotSceneLoader::processParticleSystem (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent) [protected]
Definition at line 721 of file DotSceneLoader.cpp.
References getAttrib(), and mSceneMgr.
Referenced by processNode().
void DotSceneLoader::processPlane (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent) [protected]
Definition at line 744 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), getAttrib(), getAttribBool(), getAttribReal(), mSceneMgr, and parseVector3().
Referenced by processNode().
void DotSceneLoader::processScene (rapidxml::xml_node<> * XMLRoot) [protected]
Definition at line 105 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute(), rapidxml::xml_node< Ch >::first_node(), getAttrib(), processCamera(), processEnvironment(), processExternals(), processNodes(), processOctree(), processTerrain(), and processUserDataReference().
Referenced by parseDotScene().
void DotSceneLoader::processSkyBox (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 894 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), getAttrib(), getAttribBool(), getAttribReal(), m_sGroupName, mSceneMgr, and parseQuaternion().
Referenced by processEnvironment().
void DotSceneLoader::processSkyDome (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 916 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute(), rapidxml::xml_node< Ch >::first_node(), getAttribBool(), getAttribReal(), m_sGroupName, mSceneMgr, and parseQuaternion().
Referenced by processEnvironment().
void DotSceneLoader::processSkyPlane (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 940 of file DotSceneLoader.cpp.
References getAttrib(), getAttribBool(), getAttribReal(), m_sGroupName, and mSceneMgr.
Referenced by processEnvironment().
void DotSceneLoader::processTerrain (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 254 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute(), rapidxml::xml_node< Ch >::first_node(), getAttribBool(), getAttribReal(), mSceneMgr, mTerrainGlobalOptions, mTerrainGroup, rapidxml::xml_node< Ch >::next_sibling(), and processTerrainPage().
Referenced by processScene().
void DotSceneLoader::processTerrainPage (rapidxml::xml_node<> * XMLNode) [protected]
Definition at line 306 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute(), getAttrib(), and mTerrainGroup.
Referenced by processTerrain().
void DotSceneLoader::processTrackTarget (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent) [protected]
Definition at line 641 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_node(), getAttrib(), mSceneMgr, and parseVector3().
Referenced by processNode().
void DotSceneLoader::processUserDataReference (rapidxml::xml_node<> * XMLNode, Ogre::Entity * pEntity) [protected]
Definition at line 1123 of file DotSceneLoader.cpp.
References rapidxml::xml_node< Ch >::first_attribute().
void DotSceneLoader::processUserDataReference (rapidxml::xml_node<> * XMLNode, Ogre::SceneNode * pParent = 0) [protected]
Definition at line 319 of file DotSceneLoader.cpp.
Referenced by processEntity(), processEnvironment(), processNode(), and processScene().
Member Data Documentation
std::vector<Ogre::String> DotSceneLoader::dynamicObjects
Definition at line 67 of file DotSceneLoader.h.
Referenced by parseDotScene(), and processEntity().
Ogre::String DotSceneLoader::m_sGroupName [protected]
Definition at line 129 of file DotSceneLoader.h.
Referenced by parseDotScene(), processEntity(), processSkyBox(), processSkyDome(), and processSkyPlane().
Ogre::String DotSceneLoader::m_sPrependNode [protected]
Definition at line 130 of file DotSceneLoader.h.
Referenced by parseDotScene(), and processNode().
Ogre::SceneNode* DotSceneLoader::mAttachNode [protected]
Definition at line 128 of file DotSceneLoader.h.
Referenced by parseDotScene(), processCamera(), processNode(), and processNodes().
Ogre::Vector3 DotSceneLoader::mLightDirection [protected]
Definition at line 133 of file DotSceneLoader.h.
Referenced by processLight().
std::vector<Forests::PagedGeometry *> DotSceneLoader::mPGHandles
Definition at line 68 of file DotSceneLoader.h.
Ogre::SceneManager* DotSceneLoader::mSceneMgr [protected]
Definition at line 127 of file DotSceneLoader.h.
Referenced by parseDotScene(), processCamera(), processEntity(), processEnvironment(), processFog(), processLight(), processLookTarget(), processPagedGeometry(), processParticleSystem(), processPlane(), processSkyBox(), processSkyDome(), processSkyPlane(), processTerrain(), and processTrackTarget().
Ogre::TerrainGlobalOptions* DotSceneLoader::mTerrainGlobalOptions
Definition at line 49 of file DotSceneLoader.h.
Referenced by DotSceneLoader(), processTerrain(), and ~DotSceneLoader().
Ogre::TerrainGroup* DotSceneLoader::mTerrainGroup [protected]
Definition at line 131 of file DotSceneLoader.h.
Referenced by getTerrainGroup(), processTerrain(), processTerrainPage(), and ~DotSceneLoader().
Ogre::Vector3 DotSceneLoader::mTerrainPosition [protected]
Definition at line 132 of file DotSceneLoader.h.
std::vector<Forests::TreeLoader3D *> DotSceneLoader::mTreeHandles
Definition at line 69 of file DotSceneLoader.h.
std::vector<nodeProperty> DotSceneLoader::nodeProperties
Definition at line 65 of file DotSceneLoader.h.
Referenced by getProperty().
std::vector<Ogre::String> DotSceneLoader::staticObjects
Definition at line 66 of file DotSceneLoader.h.
Referenced by parseDotScene(), and processEntity().
The documentation for this class was generated from the following files:
/home/bmonkey/workspace/Ogre/Collage/include/DotSceneLoader.h
/home/bmonkey/workspace/Ogre/Collage/src/Core/DotSceneLoader.cpp