Collage: rapidxml::xml_document< Ch >::whitespace_pred Struct Reference
rapidxml::xml_document< Ch >::whitespace_pred Struct Reference
Static Public Member Functions
static unsigned char test (Ch ch)
Detailed Description
template<class Ch = char>
struct rapidxml::xml_document< Ch >::whitespace_pred
Definition at line 1428 of file rapidxml.hpp.
Member Function Documentation
template<class Ch = char> static unsigned char rapidxml::xml_document< Ch >::whitespace_pred::test (Ch ch) [inline, static]
Definition at line 1430 of file rapidxml.hpp.
Referenced by rapidxml::xml_document< Ch >::parse_and_append_data(), rapidxml::xml_document< Ch >::parse_node(), and rapidxml::xml_document< Ch >::skip_and_expand_character_refs().
The documentation for this struct was generated from the following file:
/home/bmonkey/workspace/Ogre/Collage/include/rapidxml.hpp